
name: Python simple test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Installing package list
      run: apt list --installed    
    - name: Removing previous chrome instances on runner 
      run: sudo apt purge google-chrome-stable 
    - name: Install dependencies
      run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay pytest
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Run Python script 
      run: |
        pytest -s
